bot:
  yard:
    start-max-xp: 6
    start-max-loot: 2
  inventory:
    max-bad-food-satiety: 15
    max-minus-xp-bad-food: 10
  username: ${BOT_USERNAME:cat_test_bot}
  token: ${BOT_TOKEN:7163221375:AAFsAoG3Bz-jUiQyWx3ky9uBKcke8yd3Q2M}
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cat_bot}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  application:
    name: CatBot
  devtools:
    restart:
      enabled: false
cron:
  check-satiety: 0 0 * * * * #Раз в час